base_lr: 0.1
batch_size: 64
config: ./config/tdgcn_V2.yaml
device:
- 4
eval_interval: 5
feeder: feeders.feeder.Feeder
ignore_weights: []
log_interval: 100
model: model.tdgcn_xy.Model
model_args:
  graph: graph.this_graph.Graph
  graph_args:
    labeling_mode: spatial
  num_class: 155
  num_person: 2
  num_point: 17
model_saved_name: ./runs/tdgcn_V2
nesterov: true
num_epoch: 65
num_worker: 32
only_train_epoch: 0
only_train_part: false
optimizer: SGD
phase: train
print_log: true
save_interval: 1
save_score: true
seed: 1
show_topk:
- 1
- 5
start_epoch: 0
step:
- 35
- 55
test_batch_size: 256
test_feeder_args:
  data_path: ./data/test_bone_A.npy
  label_path: ./data/test_label_A.pkl
train_feeder_args:
  data_path: ./data/train_bone.npy
  debug: false
  label_path: ./data/train_label.pkl
  normalization: false
  random_choose: false
  random_move: false
  random_shift: false
  window_size: -1
warm_up_epoch: 5
weight_decay: 0.0001
weights: null
work_dir: ./work_dir/tdgcn_V2
