work_dir: ./work_dir/agcn_joint
model_saved_name: ./runs/agcn_joint
# feeder
feeder: feeders.feeder.Feeder
train_feeder_args:
  data_path: ./data/train_data_joint.npy
  label_path: ./data/train_label.npy
  debug: False
  random_choose: False
  random_shift: False
  random_move: False
  window_size: -1
  normalization: False

test_feeder_args:
  data_path: ./data/test_joint_A.npy
  label_path: /data/test_label_A.npy

# model
model: model.agcn.Model
model_args:
  num_class: 60
  num_point: 25
  num_person: 2
  graph: graph.this_graph.Graph
  graph_args:
    labeling_mode: 'spatial'

#optim
weight_decay: 0.0001
base_lr: 0.1
step: [30, 40]

# training
device: [0, 1 ,2, 3]
batch_size: 64
test_batch_size: 64
num_epoch: 50
nesterov: True
