work_dir: ./work_dir/agcn_bone
model_saved_name: ./runs/agcn_bone
# feeder
feeder: feeders.feeder.Feeder
train_feeder_args:
  data_path: ./data/train_bone.npy
  label_path: ./data/train_label.pkl
  debug: False
  random_choose: False
  random_shift: False
  random_move: False
  window_size: -1
  normalization: False

test_feeder_args:
  data_path: ./data/test_joint_A.npy
  label_path: ./data/test_label_A.pkl

# model
model: model.agcn.Model
model_args:
  num_class: 155
  num_point: 17
  num_person: 2
  graph: graph.this_graph.Graph
  graph_args:
    labeling_mode: 'spatial'

#optim
weight_decay: 0.0003
base_lr: 0.1
step: [30,40]

# training
device: [0,1,2]
batch_size: 64
test_batch_size: 256
num_epoch: 50
nesterov: True
