base_lr: 0.01
batch_size: 256
config: ./config/test_bone.yaml
device:
- 1
eval_interval: 5
feeder: feeders.feeder.Feeder
ignore_weights: []
log_interval: 100
model: model.ctrgcn_xyz.Model
model_args:
  graph: graph.this_graph.Graph
  graph_args:
    labeling_mode: spatial
  num_class: 155
  num_person: 2
  num_point: 17
model_saved_name: ./runs/ctrgcn_V2_B_3D_test_bone
nesterov: false
num_epoch: 80
num_worker: 32
only_train_epoch: 0
only_train_part: false
optimizer: SGD
phase: test
print_log: true
save_interval: 2
save_score: true
seed: 1
show_topk:
- 1
- 5
start_epoch: 0
step:
- 20
- 40
- 60
test_batch_size: 16
test_feeder_args:
  data_path: ./data/test_bone_A.npy
  debug: false
  label_path: ./data/test_label_A.pkl
train_feeder_args: {}
warm_up_epoch: 0
weight_decay: 0.0005
weights: /data/yangzhao/xinye/GlobalAI/real/real/runs/ctrgcn_V2_B_3D-38-9984.pt
work_dir: ./work_dir/ctrgcn_V2_B_3D_test_bone
